Parameters:
  PowerUserName:
    Description: Task-3 power User Name .
    Type: String
    Default: poweruser
  PowerUserPassword:
    NoEcho: true
    Type: String
    Description: Read Only
    MinLength: 1
    MaxLength: 41
Resources:
  DevUser:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - Fn::ImportValue: PowerUserGroup
      LoginProfile:
        Password: !Ref PowerUserPassword
      UserName: !Ref PowerUserName