Parameters:
  AdministratorUserName:
    Description: Task-3 Administartor User Name .
    Type: String
    Default: administrator
  AdministartorPassword:
    NoEcho: true
    Type: String
    Description: Read Only
    MinLength: 1
    MaxLength: 41
Resources:
  DevUser:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - Fn::ImportValue: AdministratorGroup
      LoginProfile:
        Password: !Ref AdministartorPassword
      UserName: !Ref AdministratorUserName